spring.application.name=feedback-system

spring.datasource.url=jdbc:postgresql://localhost:5432/feedback_system

spring.datasource.username=doanngocanh

spring.datasource.password=...
# homebrew do not require password

spring.jpa.hibernate.ddl-auto=update
# Spring Boot -> Nhìn các Entity -> Tự tạo / cập nhật bảng
#  Hibernate could change DB schema if take "update"

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Thời gian hết hạn của Token (Tính bằng mili-giây). Ở đây là 86400000 ms = 24 giờ (1 ngày)
jwt.expiration=86400000

