spring.application.name=feedback-system

spring.datasource.url=jdbc:postgresql://localhost:5432/feedback_system

spring.datasource.username=doanngocanh

spring.datasource.password=...
# homebrew do not require password

spring.jpa.hibernate.ddl-auto=update
# Spring Boot -> Nhìn các Entity -> Tự tạo / cập nhật bảng
#  Hibernate could change DB schema if take "update"

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

